<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

define('ISLANDORA_WEB_ANNOTATION_VIEW', 'view web annotations');
define('ISLANDORA_WEB_ANNOTATION_CREATE', 'create web annotations');
define('ISLANDORA_WEB_ANNOTATION_EDIT_OWN', 'edit own web annotations');
define('ISLANDORA_WEB_ANNOTATION_EDIT_ANY', 'edit any web annotations');
define('ISLANDORA_WEB_ANNOTATION_REMOVE_OWN', 'remove own web annotations');
define('ISLANDORA_WEB_ANNOTATION_REMOVE_ANY', 'remove any web annotations');

/**
 * Implements hook_menu().
 */
function islandora_oralhistories_menu() {
  $items = array();
  $items['admin/islandora/solution_pack_config/oralhistories'] = array(
    'title' => 'Oral Histories Solution Pack',
    'description' => 'Define ingest behavior and select media player.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oralhistories_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora/object/%islandora_object/edit_form/%islandora_datastream'] = array(
    'title' => 'Oral Histories Transcript Edit form',
    'description' => 'Edit transcript',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oralhistories_transcript_edit_form', 2, 4),
    'access callback' => 'islandora_datastream_access',
    'access arguments' => array(ISLANDORA_REPLACE_DATASTREAM_CONTENT, 4),
    'file' => 'includes/transcript.edit.form.inc',
    'type' => MENU_CALLBACK,
    'load arguments' => array(2),
  );
  // try ctools ajax modal form
  $items['islandora/object/%islandora_object/edit_form/%islandora_datastream/%ctools_js'] = array(
    'page callback' => 'edit_transcript_modal',
    'page arguments' => array(2, 4, 5),
    'access callback' => 'islandora_datastream_access',
    'access arguments' => array(ISLANDORA_REPLACE_DATASTREAM_CONTENT, 4),
    'file' => 'includes/transcript.edit.form.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/web_annotation/get/%islandora_web_annotation_object'] = array(
    'page callback' => 'islandora_oralhistories_web_annotation_get_callback',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_VIEW, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/web_annotation/add'] = array(
    'title' => 'Oral Histories Web Annotation',
    'description' => 'Edit Web Annotation',
    'page callback' => '_get_web_annotation_form',
//    'page arguments' => array('islandora_oralhistories_annotation_form', 2),
    'page arguments' => array(2),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );
//  $items['islandora/object/%islandora_object/web_annotation/%ctools_js'] = array(
//    'page callback' => 'edit_annotation_modal',
//    'page arguments' => array(2, 4),
//    'access callback' => 'islandora_object_manage_access_callback',
//    'access arguments' => array(
//      array(
//        ISLANDORA_MANAGE_PROPERTIES,
//        ISLANDORA_METADATA_EDIT,
//        ISLANDORA_ADD_DS,
//        ISLANDORA_PURGE,
//        ISLANDORA_INGEST,
//      ), 2),
//    'file' => 'includes/annotation.inc',
//    'type' => MENU_CALLBACK,
//  );

  $items['islandora/object/%islandora_object/web_annotation'] = array(
    'title' => 'Oral Histories Web Annotations',
    'description' => 'List Web Annotations for a given islandora object',
    'page callback' => '_retrieve_web_annotations',
    'page arguments' => array(2),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE, ISLANDORA_WEB_ANNOTATION_VIEW, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/web_annotation/create'] = array(
    'title' => 'Create Oral Histories Web Annotation',
    'description' => 'Add a new Web Annotation',
    'page callback' => '_create_web_annotation',
//    'page arguments' => array(2),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/web_annotation/remove/%'] = array(
    'title' => 'Remove Oral Histories Web Annotation',
    'description' => 'Remove an existing Web Annotation',
    'page callback' => '_remove_web_annotation',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/web_annotation/update/%'] = array(
    'title' => 'Update Oral Histories Web Annotation',
    'description' => 'Update an existing Web Annotation',
    'page callback' => '_update_web_annotation',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_WEB_ANNOTATION_CREATE, 2),
    'file' => 'includes/annotation.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function islandora_oralhistories_permission() {
  return array(
    ISLANDORA_WEB_ANNOTATION_VIEW => array(
      'title' => t('View web annotations'),
      'description' => t('View web annotations.'),
    ),
    ISLANDORA_WEB_ANNOTATION_CREATE => array(
      'title' => t('Create web annotations'),
      'description' => t('Create web annotations'),
    ),
    ISLANDORA_WEB_ANNOTATION_EDIT_OWN => array(
      'title' => t('Edit own web annotations'),
      'description' => t('edit own web annotations'),
    ),
    ISLANDORA_WEB_ANNOTATION_EDIT_ANY => array(
      'title' => t('Edit any web annotations'),
      'description' => t('edit any web annotations'),
    ),
    ISLANDORA_WEB_ANNOTATION_REMOVE_OWN => array(
      'title' => t('Remove own web annotations'),
      'description' => t('remove own web annotations'),
    ),
    ISLANDORA_WEB_ANNOTATION_REMOVE_ANY => array(
      'title' => t('Remove any web annotations'),
      'description' => t('remove any web annotations'),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_oralhistories_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  // Oral Histories Content Model.
  $oralhistories_content_model = $connection->repository->constructObject('islandora:oralhistoriesCModel');
  $oralhistories_content_model->owner = 'fedoraAdmin';
  $oralhistories_content_model->label = 'Islandora Oral Histories Content Model';
  $oralhistories_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_oralhistories_ingest__ds_composite_datastream($oralhistories_content_model,
    $module_path . "/xml/islandora_oralhistories_ds_composite_model.xml");

  // Oral Histories Collection.
  $oralhistories_collection = $connection->repository->constructObject('islandora:oralhistories_collection');
  $oralhistories_collection->owner = 'fedoraAdmin';
  $oralhistories_collection->label = 'Oral Histories Collection';
  $oralhistories_collection->models = 'islandora:collectionCModel';
  $oralhistories_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $oralhistories_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_oralhistories_collection_policy.xml", FALSE);
  $oralhistories_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $oralhistories_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $oralhistories_collection->ingestDatastream($datastream);

  // Web annotation CModel
  $wa_content_model = $connection->repository->constructObject('islandora:WADMCModel');
  $wa_content_model->owner = 'fedoraAdmin';
  $wa_content_model->label = 'Islandora Web Annotation Content Model';
  $wa_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  islandora_oralhistories_ingest__ds_composite_datastream($wa_content_model,
    $module_path . "/xml/webannotation_ds_composite_model.xml");

  return array(
    'islandora_oralhistories' => array(
      'title' => 'Islandora Oral Histories',
      'objects' => array(
        $oralhistories_content_model,
        $wa_content_model,
        $oralhistories_collection,
      ),
    ),
  );
}

/**
 * This function will add an entity DS composite datastream to an object.
 *
 * This is a workaround of a known issue with temp files being lost in Tuque in
 * batches because of object destruction during the serialization process.
 *
 * @param AbstractObject $object
 *   The object to add the DS composite datastream to.
 */
function islandora_oralhistories_ingest__ds_composite_datastream(AbstractObject $object, $filename) {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');

  $ds_composite_datastream = $object->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $ds_composite_datastream->label = 'DS-COMPOSITE-MODEL';
  $ds_composite_datastream->mimetype = 'text/xml';
  $ds_composite_datastream->setContentFromFile($filename, FALSE);
  $object->ingestDatastream($ds_composite_datastream);
}


/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_oralhistories_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  return array(
    'oralhistories MODS form' => array(
      'form_file' => "$module_path/xml/islandora_oralhistories_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_oralhistories_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_oralhistories_mods_form' => array(
      'content_model' => 'islandora:oralhistoriesCModel',
      'form_name' => 'oralhistories MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_oralhistories_theme($existing, $type, $theme, $path) {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  return array(
    'islandora_oralhistories' => array(
      'template' => 'theme/islandora-oralhistories',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_oralhistories__',
      'variables' => array(
        'object' => NULL
      ),
    ),
    'islandora_native_html5' => array(
      'template' => 'theme/islandora-native-html5',
      'file' => 'theme/theme.inc',
      'variables' => array(
        'object' => NULL,
        'params' => NULL
      ),
    ),
    'islandora_transcript_scroller' => array(
      'template' => 'theme/islandora-transcript-scroller',
      'file' => 'theme/theme.inc',
    ),
    'islandora_html5_video_stack' => array(
      'template' => 'theme/islandora-html5-video-stack',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora-html5-video-stack__',
      'variables' => array(
        'object' => NULL,
        'params' => NULL
      ),
    ),
    'islandora_html5_video_side' => array(
      'template' => 'theme/islandora-html5-video-side',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora-html5-video-side__',
      'variables' => array(
        'object' => NULL,
        'params' => NULL
      ),
    ),
    'islandora_webannotation' => array(
      'path' => $module_path . '/theme',
      'file' => 'theme.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_oralhistories', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_ingest_steps() {
  return array(
    'islandora_oralhistories_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_oralhistories_upload_form',
      'module' => 'islandora_oralhistories',
      'file' => 'includes/oralhistories_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_derivative() {
  $derivatives = array();

  if (variable_get('islandora_oralhistories_media_uploaded_type') == 'video') {
    if (module_exists('islandora_video') && function_exists('islandora_video_islandora_sp_videoCModel_islandora_derivative')) {
      $derivatives = islandora_video_islandora_sp_videoCModel_islandora_derivative();
    } else {
      drupal_set_message(t('Error in creating video derivatives. Cannot find required functions.'), 'error', FALSE);
      drupal_exit();
    }
  }


  if (variable_get('islandora_oralhistories_media_uploaded_type') == 'audio') {
    if (module_exists('islandora_video') && function_exists('islandora_video_islandora_sp_videoCModel_islandora_derivative')) {
      $derivatives = islandora_audio_islandora_sp_audiocmodel_islandora_derivative();
    } else {
      drupal_set_message(t('Error in creating audio derivatives. Cannot find required functions.'), 'error', FALSE);
      drupal_exit();
    }
  }
  if (variable_get('islandora_oralhistories_make_vtt', TRUE)) {
    $derivatives[] = array(
      'source_dsid' => 'TRANSCRIPT',
      'destination_dsid' => 'MEDIATRACK',
      'function' => array(
        'islandora_oralhistories_create_vtt',
      ),
      'file' => drupal_get_path('module', 'islandora_oralhistories') . '/includes/derivatives.inc',
    );
  }
  return $derivatives;
}

/**
 * Implements hook_transcripts_ui_js_alter().
 */
function islandora_oralhistories_transcripts_ui_js_alter(&$scripts) {
  $scripts['ui'] = drupal_get_path('module', 'islandora_oralhistories') . '/js/transcripts_ui.js';
}

/**
 * Implements hook_theme_registry_alter().
 *
 * So we can have theme_transcripts_ui_transcript_navigation().
 */
function islandora_oralhistories_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  if ($theme_registry['transcripts_ui_transcript_navigation']['function'] == 'theme_transcripts_ui_transcript_navigation') {
    $theme_registry['transcripts_ui_transcript_navigation']['theme path'] = $module_path;
    $theme_registry['transcripts_ui_transcript_navigation']['function'] = 'islandora_transcript_navigation';
  }
}

/**
 * Overrides theme_transcripts_ui_transcript_navigation() to have 'edit' button.
 *
 * @param $vars
 * @return string
 */
function islandora_transcript_navigation(array &$variables) {
  module_load_include('inc', 'islandora_oralhistories', 'includes/transcript.edit.form');
  $path = current_path();
  $part_parts = explode('/', $path);
  $object = islandora_object_load($part_parts[2]);

  $out = "<div class='btn-group' role='group'>";
  $out .= "<button type='button' class='btn btn-default previous' title='Previous line'><span class='glyphicon glyphicon-arrow-left'></span> " . t('Prev') . "</button>";
  $out .= "<button type='button' class='btn btn-default sameagain' title='Same line'><span class='glyphicon glyphicon-repeat'></span> " . t('Same') . "</button>";
  $out .= "<button type='button' class='btn btn-default next' title='Next line'><span class='glyphicon glyphicon-arrow-right'></span> " . t('Next') . "</button>";
  if (isset($object['TRANSCRIPT']) && islandora_datastream_access(ISLANDORA_REPLACE_DATASTREAM_CONTENT, $object['TRANSCRIPT'])) {
    ctools_include('modal');
    ctools_modal_add_js();
    global $base_url;

//    $link = l(t('Edit'), "/$object->id/edit_form/{$object['TRANSCRIPT']->id}/nojs", array('attributes' => array('class' => 'btn btn-default edit ctools-use-modal')));
    $out .= "<a id='transcript-edit' class='btn btn-default edit ctools-use-modal' title='Edit' href='" . $base_url . "/islandora/object/{$object->id}/edit_form/{$object['TRANSCRIPT']->id}/nojs";
    $out .= "'><span class='glyphicon glyphicon-edit'></span> " . t('Edit') . "</a>";
//    $out .= "<div id='transcript-edit-dialog'>";
//    $form = drupal_get_form('islandora_oralhistories_transcript_edit_form', $object, $object['TRANSCRIPT']);
    // Hide submit button.
//    hide($form['actions']);
//
//    $out .= drupal_render($form);
//    $out .= "</div>";
  }
  $out .= "</div>";
  return $out;
}


/**
 * Implements hook_islandora_edit_datastream_registry().
 */
function islandora_oralhistories_islandora_edit_datastream_registry(AbstractObject $object, AbstractDatastream $datastream) {
  if (strtoupper($datastream->id)  == 'TRANSCRIPT') {
    return array(
      array(
        'name' => t('Islandora Oralhistories Edit Transcript'),
        'url' => "islandora/object/{$object->id}/edit_form/{$datastream->id}",
      ),
    );
  }
}


