<?php

/**
 * @file
 * Hooks for installing/unintstalling this module.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_oralhistories_islandora_required_objects()
 */
function islandora_oralhistories_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_oralhistories');
}

/**
 * Implements hook_uninstall().
 */
function islandora_oralhistories_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $variables = array(
    'islandora_oralhistories_viewers',
    'islandora_oralhistories_ffmpeg_path',
    'islandora_oralhistories_retain_original',
    'islandora_oralhistories_make_archive',
    'islandora_oralhistories_make_mp4_locally',
    'islandora_oralhistories_make_ogg_locally',
    'islandora_oralhistories_ffmpeg2theora_path',
  );
  array_map('variable_del', $variables);
  islandora_install_solution_pack('islandora_oralhistories', 'uninstall');
}

