<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function islandora_oralhistories_menu() {
  $items = array();
  $items['admin/islandora/solution_pack_config/oralhistories'] = array(
    'title' => 'Oral Histories Solution Pack',
    'description' => 'Define ingest behavior and select media player.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_oralhistories_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_islandora_required_objects().
 */
function islandora_oralhistories_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  // Oral Histories Content Model.
  $oralhistories_content_model = $connection->repository->constructObject('islandora:oralhistoriesCModel');
  $oralhistories_content_model->owner = 'fedoraAdmin';
  $oralhistories_content_model->label = 'Islandora Oral Histories Content Model';
  $oralhistories_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $oralhistories_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_oralhistories_ds_composite_model.xml", FALSE);
  $oralhistories_content_model->ingestDatastream($datastream);

  // Oral Histories Collection.
  $oralhistories_collection = $connection->repository->constructObject('islandora:oralhistories_collection');
  $oralhistories_collection->owner = 'fedoraAdmin';
  $oralhistories_collection->label = 'Oral Histories Collection';
  $oralhistories_collection->models = 'islandora:collectionCModel';
  $oralhistories_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $oralhistories_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_oralhistories_collection_policy.xml", FALSE);
  $oralhistories_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $oralhistories_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $oralhistories_collection->ingestDatastream($datastream);
  return array(
    'islandora_oralhistories' => array(
      'title' => 'Islandora Oral Histories',
      'objects' => array(
        $oralhistories_content_model,
        $oralhistories_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_oralhistories_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_oralhistories');
  return array(
    'oralhistories MODS form' => array(
      'form_file' => "$module_path/xml/islandora_oralhistories_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_oralhistories_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_oralhistories_mods_form' => array(
      'content_model' => 'islandora:oralhistoriesCModel',
      'form_name' => 'oralhistories MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_oralhistories_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_oralhistories' => array(
      'template' => 'theme/islandora-oralhistories',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_oralhistories__',
      'variables' => array(
        'object' => NULL
      ),
    ),
    'islandora_native_html5' => array(
      'template' => 'theme/islandora-native-html5',
      'file' => 'theme/theme.inc',
      'variables' => array(
        'object' => NULL,
        'params' => NULL
      ),
    ),
    'islandora_transcript_scroller' => array(
      'template' => 'theme/islandora-transcript-scroller',
      'file' => 'theme/theme.inc',
    ),
    'islandora_html5_video' => array(
      'path' => drupal_get_path('module', 'islandora_oralhistories') . '/theme',
      'file' => 'theme.inc',
      'variables' => array(
        'object' => NULL,
        'params' => NULL
      ),
    ),
    'islandora_link_tcu' => array(
      'path' => drupal_get_path('module', 'islandora_oralhistories') . '/theme',
      'file' => 'theme.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_oralhistories', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_ingest_steps() {
  return array(
    'islandora_oralhistories_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_oralhistories_upload_form',
      'module' => 'islandora_oralhistories',
      'file' => 'includes/oralhistories_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_oralhistories_islandora_oralhistoriesCModel_islandora_derivative() {
  $derivatives = array();

  if (variable_get('islandora_oralhistories_media_uploaded_type') == 'video') {
    if (module_exists('islandora_video') && function_exists('islandora_video_islandora_sp_videoCModel_islandora_derivative')) {
      $derivatives = islandora_video_islandora_sp_videoCModel_islandora_derivative();
    } else {
      drupal_set_message(t('Error in creating video derivatives. Cannot find required functions.'), 'error', FALSE);
      drupal_exit();
    }
  }


  if (variable_get('islandora_oralhistories_media_uploaded_type') == 'audio') {
    if (module_exists('islandora_video') && function_exists('islandora_video_islandora_sp_videoCModel_islandora_derivative')) {
      $derivatives = islandora_audio_islandora_sp_audiocmodel_islandora_derivative();
    } else {
      drupal_set_message(t('Error in creating audio derivatives. Cannot find required functions.'), 'error', FALSE);
      drupal_exit();
    }
  }
  if (variable_get('islandora_oralhistories_make_vtt', TRUE)) {
    $derivatives[] = array(
      'source_dsid' => 'TRANSCRIPT',
      'destination_dsid' => 'MEDIATRACK',
      'function' => array(
        'islandora_oralhistories_create_vtt',
      ),
      'file' => drupal_get_path('module', 'islandora_oralhistories') . '/includes/derivatives.inc',
    );
  }
  return $derivatives;
}


